encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/search/", views.search, name="search"),
    path("wiki/create/", views.createEntry, name="create"),
    path("wiki/edit/", views.editPage, name="edit"),
    path("wiki/editPage/", views.editPageRender, name="renderEdit"),
    path("wiki/random/", views.randomEntry, name="random"),
    path("wiki/<str:name>", views.loadEntry, name="wiki"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
import markdown2, random
from . import util

def loadEntry(request, name):
    pageEntry = util.get_entry(name)
    if pageEntry == None: 
        return render(request, "encyclopedia/errors/notFound.html")

    html = markdown2.markdown(pageEntry)
    return render(request, "encyclopedia/entry.html", {
        "title" : name,
        "page" : html,
    })


def search(request):

    query = request.GET.get("q")
    pageEntry = util.get_entry(query)

    if pageEntry == None:
        result = []
        entries = util.list_entries()

        for entry in entries:
            if query.lower() in entry.lower():
                result.append(entry)

        return render(request, "encyclopedia/results.html", {
            "entries": result
        })

    html = markdown2.markdown(pageEntry)
    return render(request, "encyclopedia/entry.html", {
        "title": query,
        "page": html,
    })


def createEntry(request):

    if request.method != "POST":
        return render(request, "encyclopedia/createPage.html", {
            "error":"",
            "title": "",
            "content": ""
        })

    title = request.POST.get("title")
    content = request.POST.get("content")

    if title == "" or content == "":
        return render(request, "encyclopedia/createPage.html", {
            "error": "emptyField",
            "title": title,
            "content": content
        })

    if util.get_entry(title) != None:
        return render(request, "encyclopedia/createPage.html", {
            "error": "entryExists",
            "title": title,
            "content": content
        })
    
    util.save_entry(title, content)
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "page": markdown2.markdown(content)
    })


def editPage(request):

    if request.method != "POST":
        return render(request, "encyclopedia/errors/notFound.html")
    
    title = request.POST.get("title")
    content = request.POST.get("content")

    if content == "":
        return render(request, "encyclopedia/editPage.html", {
            "error": "emptyField",
            "title": title,
            "content": content
        })
    
    util.save_entry(title, content)
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "page": markdown2.markdown(content)
    })


def editPageRender(request):

    if request.method != "POST":
        return render(request, "encyclopedia/errors/notFound.html")

    title = request.POST.get("title")
    content = util.get_entry(title)
    return render(request, "encyclopedia/editPage.html", {
        "error":"",
        "title": title,
        "content": content,
    })


def randomEntry(request):
    entries = util.list_entries()
    luckyEntry = random.choice(entries)
    entry = util.get_entry(luckyEntry)

    html = markdown2.markdown(entry)
    return render(request, "encyclopedia/entry.html", {
        "title" : luckyEntry,
        "page" : html,
    })


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

encyclopedia/templates/encyclopedia/createPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create Page</h1>
    <br>
    <form action="{% url 'encyclopedia:create' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="pageTitle">Page Title</label>
          <input type="text" class="form-control" id="pageTitle" placeholder="title of the page you want to create.." name="title" value="{{title}}">
        </div>
        <br>
        <div class="form-group">
          <label for="pageContent">Page Content</label>
          <textarea class="form-control" id="pageContent" rows="3" name="content">{{content}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Create Page</button>
    </form>
    <br>
    <p>Note: This website uses Markdown language for its pages, to find more info on Markdown check <a href="https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax">this link</a></p>

    {% if error == "entryExists" %}
    <div class="alert alert-danger" role="alert">
        <h2> A page with this title already exists.. </h2>
    </div>
    {% elif error == "emptyField" %}
    <div class="alert alert-danger" role="alert">
      <h2> Title and content need to have text in them.. </h2>
    </div>
    {% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/editPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <h1>Edit Page Content</h1>
    <br>
    <form action="{% url 'encyclopedia:edit' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
        </div>
        <input type="hidden" name="title" value="{{title}}">
        <br>
        <div class="form-group">
          <label for="pageContent">Page Content</label>
          <textarea class="form-control" id="pageContent" rows="3" name="content">{{content}}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Edit Page</button>
    </form>
    <br>
    <p>Note: This website uses Markdown language for its pages, to find more info on Markdown check <a href="https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax">this link</a></p>

    {% if error == "emptyField" %}
    <div class="alert alert-danger" role="alert">
        <h2> page content cannot be left empty. </h2>
    </div>
    {% endif %}

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{%block title%}
    {{title}}
{% endblock %}

{%block body%}
    {{page | safe}}
    
    <br><br>
    <form action="{% url 'encyclopedia:renderEdit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{title}}">
        <input type="submit" class="link-button" value="Edit Page Content"/>
    </form>
{%endblock%}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki' name=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}?{% now 'U' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href ="{% url 'encyclopedia:random' %}"> Random Page </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Result</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki' name=entry %}">{{ entry }}</a></li>
            {%empty%}
            <h3> no results </h3>
        {% endfor %}
    </ul>

{% endblock %}